---
- name: Deploy IaC for MediaWiki
  tags:
    - iac
  block:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ az_rg_name }}"
        location: westus
        tags:
          testing: testing

    - name: Create a virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ az_rg_name }}"
        name: myVirtualNetwork
        address_prefixes_cidr:
          - 10.1.0.0/16
          - 172.100.0.0/16
        dns_servers:
          - 127.0.0.1
          - 127.0.0.2
        tags:
          testing: testing

    - name: Create a subnet refer nsg from other resource group
      azure_rm_subnet:
        resource_group: "{{ az_rg_name }}"
        virtual_network_name: myVirtualNetwork
        name: mySubnet
        address_prefix_cidr: "10.1.0.0/16"
        security_group:
          name: secgroupfoo
          resource_group: mySecondResourceGroup
        route_table: route

    - name: Create a network interface with minimal parameters
      azure_rm_networkinterface:
        name: nic001
        resource_group: "{{ az_rg_name }}"
        virtual_network: vnet001
        subnet_name: subnet001
        ip_configurations:
          - name: ipconfig1
            public_ip_address_name: publicip001
            primary: true

    - name: Create VM with defaults
      azure_rm_virtualmachine:
        resource_group: "{{ az_rg_name }}"
        name: testvm10
        admin_username: "{{ username }}"
        admin_password: "{{ password }}"
        image:
          offer: Red Hat
          publisher: OpenLogic
          sku: "7.1"
          version: latest
        os_disk_size_gb: 512
        state: present
        started: true
        vm_size: Standard_D4
        boot_diagnostics:
          enabled: true
          type: managed
        network_interfaces: testvm001
